/*
 * Copyright (c) 2010-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Vanaheimr Hermod <https://www.github.com/Vanaheimr/Hermod>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using NUnit.Framework;

using Newtonsoft.Json;

#endregion

namespace org.GraphDefined.Vanaheimr.Hermod.Tests.TOTP
{

    /// <summary>
    /// Runs the TOTPGenerator against the canonical conformance test vectors in
    /// TOTP/TestVectors/ - vendored, byte for byte, from
    /// https://github.com/OpenChargingCloud/TOTPConformanceTests (TestVectors/),
    /// where they are generated by an independent reference implementation and
    /// also run against TOTP.ts. Regenerate them THERE
    /// (tools/generate-test-vectors.py mirrors them into this folder); the
    /// conformance suite fails when this copy drifts.
    /// </summary>
    [TestFixture]
    public class TOTPVectorTests
    {

        #region Data / vector file models

        private const String ImplementationName = "hermod";

        /// <summary>
        /// The optional capabilities this implementation provides
        /// ("requires" lists of vectors).
        /// </summary>
        private static readonly HashSet<String> capabilities = [ "tlsChannelBinding" ];


        public sealed class VectorFile<T>
        {
            public List<T>  Vectors  { get; set; } = [];
        }

        public sealed class GenerationVector
        {
            public String          Id        { get; set; } = "";
            public VectorInput     Input     { get; set; } = new();
            public VectorExpected  Expected  { get; set; } = new();
            public List<String>?   Requires  { get; set; }
            public override String ToString() => Id;
        }

        public sealed class VectorInput
        {
            public String   SharedSecret            { get; set; } = "";
            public Int64    UnixTimestampMillis     { get; set; }
            public Double?  ValidityTimeSeconds     { get; set; }
            public Double?  TotpLength              { get; set; }
            public String?  Alphabet                { get; set; }
            public String?  HashAlgorithm           { get; set; }
            public String?  TlsExporterMaterialHex  { get; set; }
        }

        public sealed class VectorExpected
        {
            public String  Previous              { get; set; } = "";
            public String  Current               { get; set; } = "";
            public String  Next                  { get; set; } = "";
            public Int32   RemainingTimeSeconds  { get; set; }
        }

        public sealed class InvalidInputVector
        {
            public String         Id               { get; set; } = "";
            public VectorInput    Input            { get; set; } = new();
            public String         ExpectedError    { get; set; } = "";
            public List<String>?  KnownDeviations  { get; set; }
            public List<String>?  NotApplicable    { get; set; }
            public override String ToString() => Id;
        }


        private static VectorFile<T> Load<T>(String FileName)
        {

            var path = Path.Combine(AppContext.BaseDirectory, "TOTP", "TestVectors", FileName);

            return JsonConvert.DeserializeObject<VectorFile<T>>(File.ReadAllText(path))
                       ?? throw new InvalidOperationException($"Could not parse '{path}'!");

        }

        public static IEnumerable<TestCaseData> GenerationVectors()
            => Load<GenerationVector>("totp-test-vectors.json").Vectors
                   .Select(vector => new TestCaseData(vector).SetArgDisplayNames(vector.Id));

        public static IEnumerable<TestCaseData> InvalidInputVectors()
            => Load<InvalidInputVector>("totp-invalid-inputs.json").Vectors
                   .Select(vector => new TestCaseData(vector).SetArgDisplayNames(vector.Id));

        #endregion


        #region VectorFilesAreLoaded

        [Test]
        public void VectorFilesAreLoaded()
        {
            Assert.Multiple(() => {
                Assert.That(GenerationVectors().Count(),    Is.GreaterThanOrEqualTo(30));
                Assert.That(InvalidInputVectors().Count(),  Is.GreaterThanOrEqualTo(15));
            });
        }

        #endregion

        #region KnownCapabilitiesOnly

        /// <summary>
        /// Every "requires" entry must name a capability this suite knows about,
        /// so that a new capability in the vector files cannot be skipped silently.
        /// </summary>
        [Test]
        public void KnownCapabilitiesOnly()
        {

            var unknown = Load<GenerationVector>("totp-test-vectors.json").Vectors
                              .SelectMany(vector => vector.Requires ?? [])
                              .Where(capability => !capabilities.Contains(capability))
                              .Distinct()
                              .ToList();

            Assert.That(unknown, Is.Empty,
                        $"Unknown capabilities in the vector file: {String.Join(", ", unknown)}");

        }

        #endregion


        #region GenerateTOTPs (vector-driven)

        [TestCaseSource(nameof(GenerationVectors))]
        public void GenerateTOTPs(GenerationVector Vector)
        {

            var input          = Vector.Input;

            var hashAlgorithm  = default(TOTPHashAlgorithm?);
            if (input.HashAlgorithm is not null)
            {
                Assert.That(TOTPHashAlgorithmExtensions.TryParse(input.HashAlgorithm, out var parsed),
                            Is.True,
                            $"Could not parse hash algorithm '{input.HashAlgorithm}'!");
                hashAlgorithm = parsed;
            }

            var timestamp      = DateTimeOffset.FromUnixTimeMilliseconds(input.UnixTimestampMillis);

            var (previous,
                 current,
                 next,
                 remainingTime,
                 endTime)      = TOTPGenerator.GenerateTOTPs(

                                     input.SharedSecret,

                                     input.ValidityTimeSeconds is Double validityTime
                                         ? TimeSpan.FromSeconds(validityTime)
                                         : null,

                                     input.TotpLength is Double totpLength
                                         ? (UInt32) totpLength
                                         : null,

                                     input.Alphabet,
                                     timestamp,

                                     input.TlsExporterMaterialHex is String hex
                                         ? Convert.FromHexString(hex)
                                         : null,

                                     hashAlgorithm

                                 );

            Assert.Multiple(() => {
                Assert.That(previous,       Is.EqualTo(Vector.Expected.Previous),  "previous");
                Assert.That(current,        Is.EqualTo(Vector.Expected.Current),   "current");
                Assert.That(next,           Is.EqualTo(Vector.Expected.Next),      "next");
                Assert.That(remainingTime,  Is.EqualTo(TimeSpan.FromSeconds(Vector.Expected.RemainingTimeSeconds)));
                Assert.That(endTime,        Is.EqualTo(timestamp + remainingTime), "endTime");
            });

        }

        #endregion

        #region RejectsInvalidInput (vector-driven)

        [TestCaseSource(nameof(InvalidInputVectors))]
        public void RejectsInvalidInput(InvalidInputVector Vector)
        {

            if (Vector.NotApplicable?.Contains(ImplementationName) == true)
                Assert.Ignore("Not representable in the typed C# API - rejected by construction.");

            if (Vector.KnownDeviations?.Contains(ImplementationName) == true)
                Assert.Ignore("Documented deviation - see the conformance repository.");

            var input = Vector.Input;

            // The hash algorithm arrives as an enum: an unknown algorithm name is
            // rejected at the parsing boundary, which is this implementation's
            // conformant rejection point for these vectors.
            if (input.HashAlgorithm is not null &&
               !TOTPHashAlgorithmExtensions.TryParse(input.HashAlgorithm, out _))
            {
                Assert.Pass($"Rejected at the parsing boundary: TryParse(\"{input.HashAlgorithm}\") returned false.");
            }

            var exception = Assert.Catch<Exception>(() => {

                TOTPGenerator.GenerateTOTPs(

                    input.SharedSecret,

                    input.ValidityTimeSeconds is Double validityTime
                        ? TimeSpan.FromSeconds(validityTime)
                        : null,

                    input.TotpLength is Double totpLength
                        ? (UInt32) totpLength
                        : null,

                    input.Alphabet,
                    DateTimeOffset.FromUnixTimeMilliseconds(input.UnixTimestampMillis)

                );

            });

            Assert.That(exception?.Message,
                        Does.StartWith(Vector.ExpectedError),
                        $"Expected the shared error message for vector '{Vector.Id}'!");

        }

        #endregion

    }

}
