/*
 * Copyright (c) 2010-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Vanaheimr Hermod <https://www.github.com/Vanaheimr/Hermod>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Diagnostics;

using NUnit.Framework;

using org.GraphDefined.Vanaheimr.Hermod;
using org.GraphDefined.Vanaheimr.Hermod.SSH;

#endregion

namespace org.GraphDefined.Vanaheimr.Hermod.SSH.Tests
{

    /// <summary>
    /// Interoperability tests for public-key authentication: the real OpenSSH client authenticates to our
    /// server with a key generated by <c>ssh-keygen</c>, and our server verifies the signature (RFC 4252 §7).
    /// </summary>
    [TestFixture]
    [Category("Interop")]
    [Category("Interop.OpenSSH")]
    public class OpenSshAuthInteropTests
    {

        #region (static) tool discovery

        private static String? FindOnPathOrSystem(String Tool)
        {

            foreach (var dir in (Environment.GetEnvironmentVariable("PATH") ?? "").Split(Path.PathSeparator))
            {
                foreach (var name in new[] { Tool, Tool + ".exe" })
                {
                    try
                    {
                        var candidate = Path.Combine(dir.Trim(), name);
                        if (File.Exists(candidate))
                            return candidate;
                    }
                    catch { /* ignore malformed PATH entries */ }
                }
            }

            var system = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "OpenSSH", Tool + ".exe");
            return File.Exists(system) ? system : null;

        }

        #endregion


        #region OurServer_AuthenticatesRealOpenSshClient_WithPublicKey

        [Test]
        [CancelAfter(30000)]
        [TestCase("ed25519")]
        [TestCase("ecdsa")]
        [TestCase("rsa")]
        public async Task OurServer_AuthenticatesRealOpenSshClient_WithPublicKey(String KeyType, CancellationToken CancellationToken)
        {

            var ssh        = FindOnPathOrSystem("ssh");
            var sshKeygen  = FindOnPathOrSystem("ssh-keygen");
            if (ssh is null || sshKeygen is null)
                Assert.Ignore("No 'ssh'/'ssh-keygen' found — skipping OpenSSH public-key auth interop.");

            var keyPath = Path.Combine(Path.GetTempPath(), "hermod_authtest_" + Guid.NewGuid().ToString("N"));

            try
            {

                // 1. Generate a fresh unencrypted key pair with ssh-keygen.
                using (var keygen = Process.Start(new ProcessStartInfo(sshKeygen!)
                {
                    ArgumentList  = { "-t", KeyType, "-f", keyPath, "-N", "", "-q", "-C", "hermod-interop" },
                    UseShellExecute = false, CreateNoWindow = true, RedirectStandardError = true
                })!)
                {
                    await keygen.WaitForExitAsync(CancellationToken);
                    if (keygen.ExitCode != 0)
                        Assert.Ignore($"ssh-keygen failed for {KeyType}: {await keygen.StandardError.ReadToEndAsync(CancellationToken)}");
                }

                // 2. Parse the public key blob from "<type> <base64> <comment>".
                var publicLine  = (await File.ReadAllTextAsync(keyPath + ".pub", CancellationToken)).Split(' ', StringSplitOptions.RemoveEmptyEntries);
                var publicBlob  = Convert.FromBase64String(publicLine[1]);

                var authenticator = SshUserAuthenticator.ForAuthorizedKeys(publicBlob);
                var hostKey       = SshHostKey.GenerateEd25519();

                using var listener = SshTcpListener.Start(new IPSocket(IPv4Address.Localhost, IPPort.Auto));
                var port = listener.LocalEndPoint.Port.ToInt32();

                var serverTask = Task.Run(async () =>
                {
                    var pipe = await listener.AcceptAsync(CancellationToken);
                    using var transport = await SshTransport.ServerHandshakeAsync(pipe, hostKey, CancellationToken: CancellationToken);
                    return await UserAuthentication.ServerAuthenticateAsync(transport, authenticator, Banner: "Authorized use only.", CancellationToken: CancellationToken);
                }, CancellationToken);

                var knownHosts = Path.GetTempFileName();
                var emptyConf  = Path.GetTempFileName();

                using var client = new Process { StartInfo = new ProcessStartInfo(ssh!)
                {
                    RedirectStandardError = true, RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true
                }};

                foreach (var arg in new[]
                {
                    "-F", emptyConf,
                    "-p", port.ToString(),
                    "-o", "StrictHostKeyChecking=no",
                    "-o", $"UserKnownHostsFile={knownHosts}",
                    "-i", keyPath,
                    "-o", "IdentitiesOnly=yes",
                    "-o", "PreferredAuthentications=publickey",
                    "-o", "PasswordAuthentication=no",
                    "-o", "BatchMode=yes",
                    "-o", "ConnectTimeout=10",
                    "-vv",
                    "hermoduser@127.0.0.1",
                    "exit"
                })
                    client.StartInfo.ArgumentList.Add(arg);

                String stderr = "";

                try
                {

                    client.Start();
                    var stderrTask = client.StandardError.ReadToEndAsync(CancellationToken);

                    // Our server returns once the client's signature has been verified — the proof of interop.
                    var result = await serverTask;

                    try { if (!client.HasExited) client.Kill(entireProcessTree: true); } catch { }
                    try { stderr = await stderrTask; } catch { }

                    Assert.Multiple(() => {
                        Assert.That(result.Username, Is.EqualTo("hermoduser"));
                        Assert.That(result.Method,   Is.EqualTo("publickey"));
                    });

                }
                catch (Exception e)
                {
                    try   { if (!client.HasExited) client.Kill(entireProcessTree: true); } catch { }
                    try   { stderr = await client.StandardError.ReadToEndAsync(CancellationToken); }
                    catch { }
                    TestContext.Out.WriteLine("ssh -vv stderr:\n" + stderr);
                    throw new AssertionException($"OpenSSH public-key auth interop failed for {KeyType}. ssh -vv output:\n" + stderr, e);
                }
                finally
                {
                    try { File.Delete(knownHosts); } catch { }
                    try { File.Delete(emptyConf);  } catch { }
                }

            }
            finally
            {
                try { File.Delete(keyPath);          } catch { }
                try { File.Delete(keyPath + ".pub"); } catch { }
            }

        }

        #endregion

    }

}
